{% set python_min = '3.12' %}
{% set name = "bibmon" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bibmon-{{ version }}.tar.gz
  sha256: 2c19dd935cc1bc09b3393d936ec83c1626d8b0b9511b622bdfceea75c47cefd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - scipy >=1.10
    - scikit-learn >=1.5.1
    - pandas >=2.2.2
    - matplotlib-base >=3.9.0
    - seaborn >=0.13.2
    - statsmodels >=0.14.1
    - optuna >=3.6.1

test:
  imports:
    - bibmon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/petrobras/bibmon
  summary: Library with routines for data-driven process monitoring.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - camaramm
